### ISSUE TITLE
Setup login page and system

### ISSUE THREAD

**Issue by M10Wolverine** [M10Wolverine/LassondeProjectsInventory#2]
The user should be presented with a login page that:

- asks for user credentials and logs in if correct
- denies access if incorrect
- lets users reset their password or register a new account (who will be able to use this? only capstone admin? or all students?)

This may involve creating a User model

**Comment by M10Wolverine** [comment]
Django has built in authentication systems. See: https://learndjango.com/tutorials/django-login-and-logout-tutorial

**Comment by amandhiraj** [comment]
Implemented
